### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OfficialZygorg** [YahiaTGF/MC-Odyssey-2#3]
**Describe the bug**
Modpack Fails to load

**To Reproduce**
1. Start modpack
2. Modpack crashes when almost finishing loading
3. See error

**Expected behavior**
Modpack loads without crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/43007952/141157352-59fa3066-5f3e-40fa-8af8-8b2a0d5575e6.png)

**Information (please complete the following information):**
 - OS: Windows 10
 - Modpack Version: MC Odyssey 2 Beta 7
 - Amount of RAM Allocated: 8GB
 - Java Version used: AdoptOpenJDK 16.0.1

**Additional context**
Crash log:
[crash-2021-11-10_17.54.10-fml.txt](https://github.com/YahiaTGF/MC-Odyssey-2/files/7514520/crash-2021-11-10_17.54.10-fml.txt)

**Comment by OfficialZygorg** [comment]
Updated allocated ram to 10GB, changed Java to openjdk9, crash report:
[crash-2021-11-10_18.04.05-fml.txt](https://github.com/YahiaTGF/MC-Odyssey-2/files/7514598/crash-2021-11-10_18.04.05-fml.txt)

**Comment by OfficialZygorg** [comment]
Update 3: Endergetic 3 (Not Endergenic 3) wasnt on the modpack when it downloaded, (or it was a ghost file). Downloaded manually and still errors.

**Comment by OfficialZygorg** [comment]
Update 4 (I forgor to post it, my bad): Without Endergetic 3.0.0 (Latest version) The modpack loads

**Comment by choombdev** [comment]
Dealt with over discord since it was a crash issue and not a bug, I'll attempt to reproduce the issue locally.
