### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MdBourg98** [YahiaTGF/MC-Odyssey-2#33]
**Describe the bug**
On starting game, game goes fullscreen and cuts to "Error loading mods" Screen

**To Reproduce**
Open the game.

**Expected behavior**
The game to open.

**Screenshots**
https://imgur.com/a/qaWb2ZF

**Information (please complete the following information):**
 - OS: Windows 10
 - Modpack Version: V1.2.01 [Hotfix]
 - Amount of RAM Allocated: 8192 MiB
 - Java version 16.0.1.

**Additional context**
https://pastebin.com/UTtwjUNp

**Comment by Pyrolyzed** [comment]
Try using Java 8 - 15. Java 17 is not supported.

Taken from this github issue: https://github.com/TheCBProject/CBMultipart/issues/117

**Comment by MdBourg98** [comment]
Java 8 works, didn't think it would make it that far if it didn't work.
