### ISSUE TITLE
[BUG] Building Gadget and Exchanging Gadget won't place blocks as if item is missing from inventory.

### ISSUE THREAD

**Issue by OrthoLoess** [YahiaTGF/MC-Odyssey-2#39]
**Describe the bug**
This bug has previously been described, 7 months ago, on the BG github, and was blamed on an unknown mod conflict, an update to that modpack fixed it before it was fully investigated: https://github.com/Direwolf20-MC/BuildingGadgets/issues/637
The building gadget will not place blocks. Instead it slows the preview in red, as if you do not have the required blocks in inventory. The pictures below show this being tested with cobblestone, I have tested with a variety of other blocks, with no difference. In creative mode it slows the preview normally and places correctly regardless of the presence of blocks in inventory, as expected. I believe this only affects multiplayer worlds. The Exchanging Gadget is affected the same way.

**To Reproduce**
1. Connect to a multiplayer world running pack version 1.2.01 [Hotfix]
2. Obtain a Building Gadget or an Exchanging Gadget
3. Attempt to place or exchange any block in survival mode

**Expected behavior**
The red preview and refusal to place should happen only when the required blocks are not present in inventory, otherwise the preview should not be coloured red and the blocks should be placed/exchanged.

**Screenshots**
Building Gadget won't place cobblestone, despite being present on hotbar: ![](https://i.imgur.com/5mRr4xI.png)
Exchanging Gadget showing same behaviour: ![](https://i.imgur.com/BwuvCwM.png)
Working as expected in creative mode: ![](https://i.imgur.com/viaHaKi.png)

**Information (please complete the following information):**
 - OS: Windows 10 on client, Ubuntu 20.04.1 LTS on server
 - Modpack Version: V1.2.01 [Hotfix]
 - Amount of RAM Allocated: 10G on Client, 32G on server
 - Java Version used: 64bit OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)

**Additional context**
Everyone on the server who has tested this has found the same issue.

**Comment by choombdev** [comment]
Thank you for the report, it'll be of great help!
The bug seems to have appeared in the last few updates as well, I'll try to figure out which mod specifically causes this and fix it by next patch.

**Comment by choombdev** [comment]
I've been trying to fix this ever since to no avail, I'll put it on the back burner for a bit now until i find a fix, for now, a replacement mod has been added to the pack.

**Comment by choombdev** [comment]
Fixed.

**Comment by DexWRLD** [comment]
What was the fix? I am having the same problem with it on one of the modpacks i am playing currently
