### ISSUE TITLE
[BUG] Game freezes and crashes on world creation and load

### ISSUE THREAD

**Issue by alejandro-esquivel** [YahiaTGF/MC-Odyssey-2#43]
<-- Note that if the bug is simple as 'Recipe missing for [ITEM]' or '[ITEM] is uncraftable, you can simply skip the Reproduction, Expected Behaviour and Screenshot steps -->

I've just downloaded the mod and I can't create a new world because I get an infinite loading screen in both MultiMC and GDLauncher.

**Describe the bug**
Whenever I try to create a new world, the game gets stuck in an infinite loading screen

**To Reproduce**
1. Go to 'Single player'
2. Click on 'Create World'
3. Wait
4. Infinite joining world screen

**Expected behavior**
The game should create a world and load me into it

**Information (please complete the following information):**
 - OS: Windows 11
 - Modpack Version: 1.2.01 
 - Amount of RAM Allocated: 10596 MiB
 - Java Version used: 15

**Additional context**
I've uploaded the latest.log into a [gist.](https://gist.github.com/alejandro-esquivel/d6c2e332f458dc5c9a224081c0545087#file-latest-log)

**Comment by alejandro-esquivel** [comment]
Removing CraftPresence seems to fix it.

**Comment by choombdev** [comment]
Hey, this isn't really a bug, more of a support ticket which is usually done over discord so I'll be closing this!
